branch-defaults:
  default:
    environment: cloud-env
environment-defaults:
  cloud-env:
    branch: null
    repository: null
global:
  application_name: flask
  default_ec2_keyname: aws-eb
  default_platform: python3.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
